### ISSUE TITLE
processEnum(): Argument #1 ($value) must be of type BackedEnum|UnitEnum|Illuminate\Database\Query\Expression|string, null given

### ISSUE THREAD

**Issue by rezalabbafi** [mikebronner/laravel-model-caching#457] opened 2023-11-29 10:53 UTC
i have this method in my repository 

```
protected function _builder(): Builder
    {
        $model = $this->app->make($this->model());
        $builder = $model::query();
        // SOME OTHER LINES
        return $builder;
    }
```

When I'm using Laravel model caching and call this 

`$this->_builder()->find($id)`

if $id = null then there is this error

GeneaLabs\LaravelModelCaching\CacheKey::processEnum(): Argument #1 ($value) must be of type BackedEnum|UnitEnum|Illuminate\Database\Query\Expression|string, null given, called in /var/www/html/vendor/genealabs/laravel-model-caching/src/CacheKey.php on line 429

**Comment by Restingo** [comment] 2023-12-20 16:45
Duplicate of #443, PR #456 should fix both.

**Comment by mikebronner** [comment] 2023-12-23 18:58
This should be fixed now, thanks for your patience!

**Closed by mikebronner** 2023-12-23 18:58 UTC
